[project]
name = "torrenthunt"
version = "0.1.0"
description = "ðŸ´â€â˜ ï¸ The ultimate torrent bot on telegram"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "1337x==2.0.0",
    "aiohttp==3.11.9",
    "aiosqlite==0.20.0",
    "asyncpg==0.30.0",
    "greenlet==3.1.1",
    "loguru==0.7.2",
    "pyrogram==2.0.106",
    "python-dotenv==1.0.1",
    "scikit-learn==1.5.2",
    "sentry-sdk==2.19.0",
    "sqlalchemy==2.0.36",
    "tgcrypto==1.2.5",
    "uvloop==0.21.0",
]
