[project]
name = "torrenthunt"
version = "0.1.0"
description = "ðŸ´â€â˜ ï¸ The ultimate torrent bot on telegram"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "1337x==1.2.5",
    "aiohttp==3.9.4",
    "aiosqlite==0.19.0",
    "asyncpg==0.29.0",
    "greenlet==3.0.3",
    "loguru==0.7.2",
    "pyrogram==2.0.106",
    "python-dotenv==1.0.1",
    "scikit-learn==1.5.2",
    "sentry-sdk==2.19.0",
    "sqlalchemy==2.0.25",
    "tgcrypto==1.2.5",
    "uvloop==0.19.0",
]
